### ISSUE TITLE
Error on updating hosts file (ubuntu 20)

### ISSUE THREAD

**Issue by AndroiDjo** [dvddarias/docker-hoster#10]
When i run command 
`docker run -d \                            
    -v /var/run/docker.sock:/tmp/docker.sock \
    -v /etc/hosts:/tmp/hosts \
    dvdarias/docker-hoster`
got error
`Traceback (most recent call last):
  File "hoster.py", line 135, in <module>
    main()
  File "hoster.py", line 38, in main
    update_hosts_file()
  File "hoster.py", line 107, in update_hosts_file
    while lines[-1].strip()=="": lines.pop()
IndexError: list index out of range`
and file /etc/hosts is empty.

My system is Ubuntu 20.

**Comment by PierrePetit** [comment]
Here is what I did to reslove it. On the host machine :
`sudo nano /etc/hosts`
add a line (pretty random, I used this one) : 
`127.0.0.1			localhost	 	 me.local`
and then :
`docker restart docker-hoster`

Hope this helps someone, It's the first link I found when I encountered the error :)
